### PR TITLE
Max height for panes

### PR DESCRIPTION
**Pull request by kiskoza**
I'm trying to solve #3 .

I haven't committed all codes and I still need to clean up some logic here and there, but this is a preview of what I have currently:

render1678785391929

### CODE REVIEW

**Comment by kiskoza** [comment]
hi. I've finished this PR and also included #1 in it. let me know if you need anything else to  merge it in

**Comment by mhanberg** [comment]
I'll test this out locally today, thanks!

**Comment by mhanberg** [comment]
This looks good, but it seems like the panes are correctly resizing if you change the terminal window size.

I think it's alright to merge for now, but if you have interest you could look into fixing that next.

**Comment by mhanberg** [comment]
I've released this in 0.2.0, and updated my homebrew tap (in case you were using that, you should be able to brew update && brew upgrade)

**Pull request merged**
